### ISSUE TITLE
Got an error in the seventh level after the first move

### ISSUE THREAD

**Issue by ViktorSoroka07** [al3xnag/Wappo#1]

**Comment by ViktorSoroka07** [comment]
Because of that level is not playable and there is no way to do further movements.

**Comment by al3xnag** [comment]
Thanks for the report!

**Comment by al3xnag** [comment]
7th level is playable now.

Sorry, but there are no tests in the repo that each level is completable, so if you find any more bugs, be sure to write an issue! Thank you!
