### ISSUE TITLE
Level 75 is impossible

### ISSUE THREAD

**Issue by CoderLion** [al3xnag/Wappo#10]
There might be a chance that I'm wrong but I'm pretty sure that level 75 is impossible to solve. Can you fix it? Or was that level already broken in the original game? Also thank you for keeping this game genre alive.

**Comment by al3xnag** [comment]
I managed to pass that level. I can post my steps if you want.
<img width="415" alt="image" src="https://user-images.githubusercontent.com/4932134/207066235-94bd9885-dce2-4805-a8a5-239c851f4799.png">

**Comment by CoderLion** [comment]
Wow! We finally did it but it took 4 of us to finally solve it. Thank you for the hint that it's solvable. It made me confident to bother more friends with this problem.
