### ISSUE TITLE
Level 76 constructs an infinite "wappo-monsters-combining"

### ISSUE THREAD

**Issue by CoderLion** [al3xnag/Wappo#11]
I found a way to freeze the game and make it construct an infinite amount of divs (see video).
I haven't yet figured out why but these new divs overlap with the cell below it, preventing you from clicking that cell.
Maybe the bug is in GameUI.js somwhere after line 80. Either that or it's in the CSS file, but I'm not familiar enough with CSS to find the bug.

https://user-images.githubusercontent.com/13678079/208207493-a31af6ab-8ec8-4009-a819-cfe014fbdef6.mp4

**Comment by al3xnag** [comment]
Thank you for the details and video. I'll take a look this weekend.
