### ISSUE TITLE
Level Generator

### ISSUE THREAD

**Issue by Kisamegr** [al3xnag/Wappo#2]
Hey @nag5000 

I am building a clone of the old WAPPO game myself, and with that, a level generator to automate the levels.

I was wondering, did you create any sort of generator yourself? Did you create the levels by hand? Or maybe did you took the original levels from the old game?

**Comment by al3xnag** [comment]
Hi @Kisamegr 

In fact, the levels were taken from Wappo Game for Android (see Google Play) and then converted to own format in JS. Something like reverse engineering :), but the author was notified about it. As far as I can tell, most levels match the original game, but another 1% were invented additionally (in particular, the first and last levels).

**Comment by Kisamegr** [comment]
Thanks for the information, greatly appreciated! 
Feel free to close/delete this issue if you want, didn't know another way to contact you :)
